spring:
  application:
    name: spring-mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: "jdbc:mysql://127.0.0.1:3306/info_schema?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true"
    username: root
    password: root
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
server:
  port: 8082
#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true